//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivs.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COM_MSG_JA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COM_MSG_JA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ivs.Core.Properties.COM_MSG_JA", typeof(COM_MSG_JA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tuổi Tồn Kho.
        /// </summary>
        internal static string A_CurrentAging_Import_Form {
            get {
                return ResourceManager.GetString("A_CurrentAging_Import_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Aging &gt; Stock Aging Management &gt; Import Stock Aging.
        /// </summary>
        internal static string A_CurrentAging_Import_Path {
            get {
                return ResourceManager.GetString("A_CurrentAging_Import_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is Denied. (Japanese).
        /// </summary>
        internal static string COM_MSG_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("COM_MSG_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed! (Japanese).
        /// </summary>
        internal static string COM_MSG_ACT_FAILED {
            get {
                return ResourceManager.GetString("COM_MSG_ACT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully! (Japanese).
        /// </summary>
        internal static string COM_MSG_ACT_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_ACT_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully: {1} Rows. (Japanese).
        /// </summary>
        internal static string COM_MSG_ACT_SUCCESSFULLY_AND_ROWS {
            get {
                return ResourceManager.GetString("COM_MSG_ACT_SUCCESSFULLY_AND_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel successfully!.
        /// </summary>
        internal static string COM_MSG_CANCEL_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_CANCEL_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to {0}? (Japanese).
        /// </summary>
        internal static string COM_MSG_CONFIRM_ACT {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string COM_MSG_CONFIRM_CANCEL {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データを削除しますか。.
        /// </summary>
        internal static string COM_MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容が変更されています。終了する前に保存しますか。.
        /// </summary>
        internal static string COM_MSG_CONFIRM_EXIT {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存してよろしいですか。.
        /// </summary>
        internal static string COM_MSG_CONFIRM_SAVE {
            get {
                return ResourceManager.GetString("COM_MSG_CONFIRM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has been lost. (Japanese).
        /// </summary>
        internal static string COM_MSG_CONNECTION_LOST {
            get {
                return ResourceManager.GetString("COM_MSG_CONNECTION_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot {0}, data is in use. (Japanese).
        /// </summary>
        internal static string COM_MSG_DATA_BEING_USED {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found. (Japanese).
        /// </summary>
        internal static string COM_MSG_DATA_OR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_DATA_OR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの削除に成功しました。.
        /// </summary>
        internal static string COM_MSG_DELETE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_DELETE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0}. (Japanese).
        /// </summary>
        internal static string COM_MSG_DUPPLICATE {
            get {
                return ResourceManager.GetString("COM_MSG_DUPPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already been existed. (Japanese).
        /// </summary>
        internal static string COM_MSG_EXISTED {
            get {
                return ResourceManager.GetString("COM_MSG_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not export for this category!.
        /// </summary>
        internal static string COM_MSG_EXPORT_NOT_FLOW {
            get {
                return ResourceManager.GetString("COM_MSG_EXPORT_NOT_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successfully!.
        /// </summary>
        internal static string COM_MSG_EXPORT_SUCCESSFULLY1 {
            get {
                return ResourceManager.GetString("COM_MSG_EXPORT_SUCCESSFULLY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file {0} because it is being used by another process. (Japanese).
        /// </summary>
        internal static string COM_MSG_FILE_BEING_USED {
            get {
                return ResourceManager.GetString("COM_MSG_FILE_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occurred. (Japanese).
        /// </summary>
        internal static string COM_MSG_GENERAL_EXCEPTION {
            get {
                return ResourceManager.GetString("COM_MSG_GENERAL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}. (Japanese).
        /// </summary>
        internal static string COM_MSG_GREATER_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}. (Japanese).
        /// </summary>
        internal static string COM_MSG_GREATER_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("COM_MSG_GREATER_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid [{0}]: Line [{1}]: &apos;{2}&apos; has already been existed..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_EXISTED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid [{0}]: Line [{1}] - &apos;{2}&apos; must be greater than &apos;{3}&apos;..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_GREATER_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid [{0}]: Line [{1}] - {2} is invalid..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid [{0}]: Line [{1}] - {2} must be filled in..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_LINE_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_LINE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping/Arriving items on grid {0} must be filled in..
        /// </summary>
        internal static string COM_MSG_GRID_DETAIL_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_DETAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: {1} must be fill in. (Japan).
        /// </summary>
        internal static string COM_MSG_GRID_INVENTORY_COUNTED_QTY_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_INVENTORY_COUNTED_QTY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Inventory items duplicated. (Japan).
        /// </summary>
        internal static string COM_MSG_GRID_INVENTORY_DUPLICATED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_INVENTORY_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Inventory items must be filled in. (Japan).
        /// </summary>
        internal static string COM_MSG_GRID_INVENTORY_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_INVENTORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line [{0}]: &apos;{1}&apos; must be greater than &apos;{2}&apos;..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_GREATER_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line [{0}]: {1} is invalid..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line [{0}]: {1} must be filled in..
        /// </summary>
        internal static string COM_MSG_GRID_LINE_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_LINE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record {0} of {1}.
        /// </summary>
        internal static string COM_MSG_GRID_RECORD_OF_TOTAL {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_RECORD_OF_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping/Arriving items must be filled in..
        /// </summary>
        internal static string COM_MSG_GRID_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_GRID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information has been changed. Do you want to save before exiting? (Japanese).
        /// </summary>
        internal static string COM_MSG_HAVING_CHANGE {
            get {
                return ResourceManager.GetString("COM_MSG_HAVING_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string COM_MSG_HEADERGRID_DRAG {
            get {
                return ResourceManager.GetString("COM_MSG_HEADERGRID_DRAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line [{0}]: {1} column is invalid. (Japanese).
        /// </summary>
        internal static string COM_MSG_IMPORT_LINE_INVALID {
            get {
                return ResourceManager.GetString("COM_MSG_IMPORT_LINE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line [{0}]: {1} column does not exist. (Japanese).
        /// </summary>
        internal static string COM_MSG_IMPORT_LINE_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_IMPORT_LINE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの登録に成功しました。.
        /// </summary>
        internal static string COM_MSG_INSERT_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_INSERT_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}. (Japanese).
        /// </summary>
        internal static string COM_MSG_INVALID_DATA_OR_ACTION {
            get {
                return ResourceManager.GetString("COM_MSG_INVALID_DATA_OR_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}. (Japanese).
        /// </summary>
        internal static string COM_MSG_LESS_THAN {
            get {
                return ResourceManager.GetString("COM_MSG_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}. (Japanese).
        /// </summary>
        internal static string COM_MSG_LESS_THAN_OR_EQUAL {
            get {
                return ResourceManager.GetString("COM_MSG_LESS_THAN_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be matched with {1}. (Japanese).
        /// </summary>
        internal static string COM_MSG_MATCHED_PASSWORD {
            get {
                return ResourceManager.GetString("COM_MSG_MATCHED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1 row selected. (Japanese).
        /// </summary>
        internal static string COM_MSG_MORE_ONE_ROW_SELECTED {
            get {
                return ResourceManager.GetString("COM_MSG_MORE_ONE_ROW_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row selected. (Japanese).
        /// </summary>
        internal static string COM_MSG_NO_ROW_SELECTED {
            get {
                return ResourceManager.GetString("COM_MSG_NO_ROW_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist. (Japanese).
        /// </summary>
        internal static string COM_MSG_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos; chưa trùng khớp &apos;{1}&apos;(JAPAN).
        /// </summary>
        internal static string COM_MSG_NOT_MATCH {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムデータの編集許可を持っていません.
        /// </summary>
        internal static string COM_MSG_NOT_PERMISSION_EDIT {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_PERMISSION_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムデータの編集許可を持っていません.
        /// </summary>
        internal static string COM_MSG_NOT_PERMISSION_EDIT1 {
            get {
                return ResourceManager.GetString("COM_MSG_NOT_PERMISSION_EDIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be filled in. (Japanese).
        /// </summary>
        internal static string COM_MSG_REQUIRED {
            get {
                return ResourceManager.GetString("COM_MSG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  row(s) found! (Japanese).
        /// </summary>
        internal static string COM_MSG_ROW_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_ROW_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size exceeds allowed limit ({0} KB) and cannot be saved. (Japanese).
        /// </summary>
        internal static string COM_MSG_SIZE_LIMITED {
            get {
                return ResourceManager.GetString("COM_MSG_SIZE_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving Date must be filled in..
        /// </summary>
        internal static string COM_MSG_STOCK_ARRIVING_DATE_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_ARRIVING_DATE_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel fail..
        /// </summary>
        internal static string COM_MSG_STOCK_CANCEL_FAIL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_CANCEL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer must be filled in..
        /// </summary>
        internal static string COM_MSG_STOCK_CUSTOMER_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_CUSTOMER_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number must be filled in..
        /// </summary>
        internal static string COM_MSG_STOCK_DOCUMENT_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_DOCUMENT_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行{0}：生産ラインが見つかりません。.
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Minus is not good..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_MINUS_NG {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_MINUS_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Minus is ok..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_MINUS_OK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_MINUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Item is enough..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_OUT_ENOUGH {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_OUT_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Item is lack..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_OUT_LACK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_OUT_LACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Production line is not exist in stock..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_PRODUCTION_LINE_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_PRODUCTION_LINE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Quality status is not exist in stock..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_QUALITY_STATUS_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_QUALITY_STATUS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Safety stock is dangerous..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_SAFETY_DANGEROUS {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_SAFETY_DANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: Stock type is not valid..
        /// </summary>
        internal static string COM_MSG_STOCK_GRID_STOCK_STOCK_TYPE_NOT_VALID {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_GRID_STOCK_STOCK_TYPE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code must be filled in.
        /// </summary>
        internal static string COM_MSG_STOCK_ITEM_CODE_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_ITEM_CODE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus is not good..
        /// </summary>
        internal static string COM_MSG_STOCK_MINUS_NG {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_MINUS_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus is ok..
        /// </summary>
        internal static string COM_MSG_STOCK_MINUS_OK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_MINUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is enough..
        /// </summary>
        internal static string COM_MSG_STOCK_OUT_ENOUGH {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_OUT_ENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is lack..
        /// </summary>
        internal static string COM_MSG_STOCK_OUT_LACK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_OUT_LACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory period was closed..
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_CLOSE {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory period was locked..
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_LOCK {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この期間は、システムに存在しない。.
        /// </summary>
        internal static string COM_MSG_STOCK_PERIOD_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PERIOD_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to print?.
        /// </summary>
        internal static string COM_MSG_STOCK_PRINT_CONFIRM {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_PRINT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety stock is dangerous. Continous?.
        /// </summary>
        internal static string COM_MSG_STOCK_SAFETY_DANGEROUS {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_SAFETY_DANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping date must be filled in..
        /// </summary>
        internal static string COM_MSG_STOCK_SHIPPING_DATE_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_SHIPPING_DATE_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier must be filled in..
        /// </summary>
        internal static string COM_MSG_STOCK_SUPPLIER_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_SUPPLIER_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse2 must be filled in..
        /// </summary>
        internal static string COM_MSG_STOCK_WAREHOUSE2_NO_NULL {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_WAREHOUSE2_NO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse2 does not exist..
        /// </summary>
        internal static string COM_MSG_STOCK_WAREHOUSE2_NOT_EXIST {
            get {
                return ResourceManager.GetString("COM_MSG_STOCK_WAREHOUSE2_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの更新に成功しました.
        /// </summary>
        internal static string COM_MSG_UPDATE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("COM_MSG_UPDATE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpriced transaction(s) have existed for this period. Please solve it first..
        /// </summary>
        internal static string CurrentPeriodNotEntryPrice {
            get {
                return ResourceManager.GetString("CurrentPeriodNotEntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods.
        /// </summary>
        internal static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having transfer transaction(s) that not completed in one period. Please solve it first..
        /// </summary>
        internal static string HavingTransferTransactionNotCompletedInOnePeriod {
            get {
                return ResourceManager.GetString("HavingTransferTransactionNotCompletedInOnePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping/Arriving Inquiry.
        /// </summary>
        internal static string IV_ArrivingIssueInquiry_Search_Form {
            get {
                return ResourceManager.GetString("IV_ArrivingIssueInquiry_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory &gt; Inventory Management &gt; Shipping/Arriving Inquiry.
        /// </summary>
        internal static string IV_ArrivingIssueInquiry_Search_Path {
            get {
                return ResourceManager.GetString("IV_ArrivingIssueInquiry_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string IV_ArrivingIssueInquiry_View_Form {
            get {
                return ResourceManager.GetString("IV_ArrivingIssueInquiry_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory &gt; Inventory Management &gt; Shipping/Arriving Inquiry &gt; Detail.
        /// </summary>
        internal static string IV_ArrivingIssueInquiry_View_Path {
            get {
                return ResourceManager.GetString("IV_ArrivingIssueInquiry_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string IV_InventoryInquiry_Edit_Form {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Inventory Inquiry -&gt; Edit Inventory.
        /// </summary>
        internal static string IV_InventoryInquiry_Edit_Path {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string IV_InventoryInquiry_New_Form {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Inventory Inquiry -&gt; Add.
        /// </summary>
        internal static string IV_InventoryInquiry_New_Path {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Inquiry.
        /// </summary>
        internal static string IV_InventoryInquiry_Search_Form {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Inventory Inquiry.
        /// </summary>
        internal static string IV_InventoryInquiry_Search_Path {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string IV_InventoryInquiry_View_Form {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Inventory Inquiry -&gt; View.
        /// </summary>
        internal static string IV_InventoryInquiry_View_Path {
            get {
                return ResourceManager.GetString("IV_InventoryInquiry_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string IV_PhysicalInventory_Edit_Form {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Physical Inventory -&gt; Edit.
        /// </summary>
        internal static string IV_PhysicalInventory_Edit_Path {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string IV_PhysicalInventory_New_Form {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Physical Inventory -&gt; Add.
        /// </summary>
        internal static string IV_PhysicalInventory_New_Path {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Inventory.
        /// </summary>
        internal static string IV_PhysicalInventory_Search_Form {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Physical Inventory.
        /// </summary>
        internal static string IV_PhysicalInventory_Search_Path {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string IV_PhysicalInventory_View_Form {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Physical Inventory -&gt; View.
        /// </summary>
        internal static string IV_PhysicalInventory_View_Path {
            get {
                return ResourceManager.GetString("IV_PhysicalInventory_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string IV_StockModify_Edit_Form {
            get {
                return ResourceManager.GetString("IV_StockModify_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Stock Modify -&gt; Edit.
        /// </summary>
        internal static string IV_StockModify_Edit_Path {
            get {
                return ResourceManager.GetString("IV_StockModify_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify some data in grid and check again..
        /// </summary>
        internal static string IV_StockModify_MSG_DONT_HAVE_ANY_CHANGE {
            get {
                return ResourceManager.GetString("IV_StockModify_MSG_DONT_HAVE_ANY_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line [{0}]: {1} must be different from {2}.
        /// </summary>
        internal static string IV_StockModify_MSG_ModifyQuantity_Difference_CurrentQuantity {
            get {
                return ResourceManager.GetString("IV_StockModify_MSG_ModifyQuantity_Difference_CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can modify these stock transaction..
        /// </summary>
        internal static string IV_StockModify_MSG_YOU_CAN_MODIFY_STOCK {
            get {
                return ResourceManager.GetString("IV_StockModify_MSG_YOU_CAN_MODIFY_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string IV_StockModify_New_Form {
            get {
                return ResourceManager.GetString("IV_StockModify_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Stock Modify -&gt; Add.
        /// </summary>
        internal static string IV_StockModify_New_Path {
            get {
                return ResourceManager.GetString("IV_StockModify_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Modify.
        /// </summary>
        internal static string IV_StockModify_Search_Form {
            get {
                return ResourceManager.GetString("IV_StockModify_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Stock Modify.
        /// </summary>
        internal static string IV_StockModify_Search_Path {
            get {
                return ResourceManager.GetString("IV_StockModify_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string IV_StockModify_View_Form {
            get {
                return ResourceManager.GetString("IV_StockModify_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory -&gt; Inventory Management -&gt; Stock Modify -&gt; View.
        /// </summary>
        internal static string IV_StockModify_View_Path {
            get {
                return ResourceManager.GetString("IV_StockModify_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消去.
        /// </summary>
        internal static string MasterEditForm_Clear {
            get {
                return ResourceManager.GetString("MasterEditForm_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string MasterEditForm_Edit {
            get {
                return ResourceManager.GetString("MasterEditForm_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次へ.
        /// </summary>
        internal static string MasterEditForm_Next {
            get {
                return ResourceManager.GetString("MasterEditForm_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リセット.
        /// </summary>
        internal static string MasterEditForm_Reset {
            get {
                return ResourceManager.GetString("MasterEditForm_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存して次へ.
        /// </summary>
        internal static string MasterEditForm_SaveAndNext {
            get {
                return ResourceManager.GetString("MasterEditForm_SaveAndNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メッセージ.
        /// </summary>
        internal static string MessageBoxs {
            get {
                return ResourceManager.GetString("MessageBoxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus stock have existed for this period. Please solve it first..
        /// </summary>
        internal static string MinusStockExist {
            get {
                return ResourceManager.GetString("MinusStockExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Info.
        /// </summary>
        internal static string MS_CompanyInfo_Edit_Form {
            get {
                return ResourceManager.GetString("MS_CompanyInfo_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Common -&gt; Company Info.
        /// </summary>
        internal static string MS_CompanyInfo_Edit_Path {
            get {
                return ResourceManager.GetString("MS_CompanyInfo_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Info.
        /// </summary>
        internal static string MS_CompanyInfo_New_Form {
            get {
                return ResourceManager.GetString("MS_CompanyInfo_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Common -&gt; Company Info.
        /// </summary>
        internal static string MS_CompanyInfo_New_Path {
            get {
                return ResourceManager.GetString("MS_CompanyInfo_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Employee (Japan).
        /// </summary>
        internal static string MS_Employees_Edit_Form {
            get {
                return ResourceManager.GetString("MS_Employees_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &gt; Employee &gt; Update (Japan).
        /// </summary>
        internal static string MS_Employees_Edit_Path {
            get {
                return ResourceManager.GetString("MS_Employees_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee (Japan).
        /// </summary>
        internal static string MS_Employees_New_Form {
            get {
                return ResourceManager.GetString("MS_Employees_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &gt; Employee &gt; Add (Japan).
        /// </summary>
        internal static string MS_Employees_New_Path {
            get {
                return ResourceManager.GetString("MS_Employees_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees (Japan).
        /// </summary>
        internal static string MS_Employees_Search_Form {
            get {
                return ResourceManager.GetString("MS_Employees_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &gt; Employees (Japan).
        /// </summary>
        internal static string MS_Employees_Search_Path {
            get {
                return ResourceManager.GetString("MS_Employees_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error Reason (Japanese).
        /// </summary>
        internal static string MS_ErrorReasons_Edit_Form {
            get {
                return ResourceManager.GetString("MS_ErrorReasons_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Warehouse Management -&gt; Error Reason -&gt; Edit Reason (Japanese).
        /// </summary>
        internal static string MS_ErrorReasons_Edit_Path {
            get {
                return ResourceManager.GetString("MS_ErrorReasons_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Error Reason (Japanese).
        /// </summary>
        internal static string MS_ErrorReasons_New_Form {
            get {
                return ResourceManager.GetString("MS_ErrorReasons_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Warehouse Management -&gt; Error Reason -&gt; Add Reason(Japanese).
        /// </summary>
        internal static string MS_ErrorReasons_New_Path {
            get {
                return ResourceManager.GetString("MS_ErrorReasons_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reason (Japanese).
        /// </summary>
        internal static string MS_ErrorReasons_Search_Form {
            get {
                return ResourceManager.GetString("MS_ErrorReasons_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Error Reason (Japanese).
        /// </summary>
        internal static string MS_ErrorReasons_Search_Path {
            get {
                return ResourceManager.GetString("MS_ErrorReasons_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Item (Japanese).
        /// </summary>
        internal static string MS_Items_Edit_Form {
            get {
                return ResourceManager.GetString("MS_Items_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Item Management -&gt; Items -&gt; Edit Item (Japanese).
        /// </summary>
        internal static string MS_Items_Edit_Path {
            get {
                return ResourceManager.GetString("MS_Items_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item (Japanese).
        /// </summary>
        internal static string MS_Items_New_Form {
            get {
                return ResourceManager.GetString("MS_Items_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Item Management -&gt; Items -&gt; Add Items(Japanese).
        /// </summary>
        internal static string MS_Items_New_Path {
            get {
                return ResourceManager.GetString("MS_Items_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items (Japanese).
        /// </summary>
        internal static string MS_Items_Search_Form {
            get {
                return ResourceManager.GetString("MS_Items_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Item Management -&gt; Items (Japanese).
        /// </summary>
        internal static string MS_Items_Search_Path {
            get {
                return ResourceManager.GetString("MS_Items_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Item.
        /// </summary>
        internal static string MS_Items_View_Form {
            get {
                return ResourceManager.GetString("MS_Items_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Item Management -&gt; Items -&gt; Detail Item.
        /// </summary>
        internal static string MS_Items_View_Path {
            get {
                return ResourceManager.GetString("MS_Items_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Suppliers.
        /// </summary>
        internal static string MS_Suppliers_Edit_Form {
            get {
                return ResourceManager.GetString("MS_Suppliers_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Suppliers Management -&gt; Suppliers -&gt; Edit Suppliers.
        /// </summary>
        internal static string MS_Suppliers_Edit_Path {
            get {
                return ResourceManager.GetString("MS_Suppliers_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Suppliers.
        /// </summary>
        internal static string MS_Suppliers_New_Form {
            get {
                return ResourceManager.GetString("MS_Suppliers_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt; Suppliers Management -&gt; Suppliers -&gt; Add Suppliers.
        /// </summary>
        internal static string MS_Suppliers_New_Path {
            get {
                return ResourceManager.GetString("MS_Suppliers_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string MS_Suppliers_Search_Form {
            get {
                return ResourceManager.GetString("MS_Suppliers_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt;Suppliers Management -&gt; Suppliers.
        /// </summary>
        internal static string MS_Suppliers_Search_Path {
            get {
                return ResourceManager.GetString("MS_Suppliers_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Suppliers.
        /// </summary>
        internal static string MS_Suppliers_View_Form {
            get {
                return ResourceManager.GetString("MS_Suppliers_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master -&gt;Suppliers Management -&gt; Suppliers -&gt; View Suppliers.
        /// </summary>
        internal static string MS_Suppliers_View_Path {
            get {
                return ResourceManager.GetString("MS_Suppliers_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending transfer transaction(s) have existed for this period. Please solve it first..
        /// </summary>
        internal static string PendingTransferTransactionExist {
            get {
                return ResourceManager.GetString("PendingTransferTransactionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_PriceUpdating_Edit_Form.
        /// </summary>
        internal static string PR_PriceUpdating_Edit_Form {
            get {
                return ResourceManager.GetString("PR_PriceUpdating_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_PriceUpdating_Search_Form.
        /// </summary>
        internal static string PR_PriceUpdating_Search_Form {
            get {
                return ResourceManager.GetString("PR_PriceUpdating_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price -&gt; Price Management -&gt; Price Updating .
        /// </summary>
        internal static string PR_PriceUpdating_Search_Path {
            get {
                return ResourceManager.GetString("PR_PriceUpdating_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous period has not closed yet. Please solve it first..
        /// </summary>
        internal static string PreviousPeriodNotClose {
            get {
                return ResourceManager.GetString("PreviousPeriodNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory &gt; Inventory Management &gt; Daily Inventory.
        /// </summary>
        internal static string RP_DailyInventory_Search_Path {
            get {
                return ResourceManager.GetString("RP_DailyInventory_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Inventory.
        /// </summary>
        internal static string RP_MonthlyInventory_Search_Form {
            get {
                return ResourceManager.GetString("RP_MonthlyInventory_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &gt; Report Overview &gt; Monthly Inventory.
        /// </summary>
        internal static string RP_MonthlyInventory_Search_Path {
            get {
                return ResourceManager.GetString("RP_MonthlyInventory_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Forecast.
        /// </summary>
        internal static string RP_SaleForecast_Search_Form {
            get {
                return ResourceManager.GetString("RP_SaleForecast_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &gt; Report Overview &gt; Sale Forecast.
        /// </summary>
        internal static string RP_SaleForecast_Search_Path {
            get {
                return ResourceManager.GetString("RP_SaleForecast_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return From Customer Shipping ({0}).
        /// </summary>
        internal static string ST_SA_ReturnFromCustomerShipping_New_Form {
            get {
                return ResourceManager.GetString("ST_SA_ReturnFromCustomerShipping_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Return From Customer Shipping ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SA_ReturnFromCustomerShipping_New_Path {
            get {
                return ResourceManager.GetString("ST_SA_ReturnFromCustomerShipping_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return From Customer Shipping ({0}).
        /// </summary>
        internal static string ST_SA_ReturnFromCustomerShipping_View_Form {
            get {
                return ResourceManager.GetString("ST_SA_ReturnFromCustomerShipping_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Return From Customer Shipping ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SA_ReturnFromCustomerShipping_View_Path {
            get {
                return ResourceManager.GetString("ST_SA_ReturnFromCustomerShipping_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Arriving Adjustment ({0}).
        /// </summary>
        internal static string ST_SA_StockArrivingAdjustment_New_Form {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingAdjustment_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Arriving Adjustment ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SA_StockArrivingAdjustment_New_Path {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingAdjustment_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Arriving Adjustment ({0}).
        /// </summary>
        internal static string ST_SA_StockArrivingAdjustment_View_Form {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingAdjustment_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Arriving Adjustment ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SA_StockArrivingAdjustment_View_Path {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingAdjustment_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Arriving For Purchase Order ({0}).
        /// </summary>
        internal static string ST_SA_StockArrivingForPurchaseOrder_New_Form {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingForPurchaseOrder_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Arriving For Purchase Order ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SA_StockArrivingForPurchaseOrder_New_Path {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingForPurchaseOrder_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Arriving For Purchase Order ({0}).
        /// </summary>
        internal static string ST_SA_StockArrivingForPurchaseOrder_View_Form {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingForPurchaseOrder_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Arriving For Purchase Order ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SA_StockArrivingForPurchaseOrder_View_Path {
            get {
                return ResourceManager.GetString("ST_SA_StockArrivingForPurchaseOrder_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Delivery To Supplier ({0}).
        /// </summary>
        internal static string ST_SH_ReturnDeliveryToSupplier_New_Form {
            get {
                return ResourceManager.GetString("ST_SH_ReturnDeliveryToSupplier_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Return Delivery To Supplier ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SH_ReturnDeliveryToSupplier_New_Path {
            get {
                return ResourceManager.GetString("ST_SH_ReturnDeliveryToSupplier_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Delivery To Supplier ({0}).
        /// </summary>
        internal static string ST_SH_ReturnDeliveryToSupplier_View_Form {
            get {
                return ResourceManager.GetString("ST_SH_ReturnDeliveryToSupplier_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Return Delivery To Supplier ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SH_ReturnDeliveryToSupplier_View_Path {
            get {
                return ResourceManager.GetString("ST_SH_ReturnDeliveryToSupplier_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapping From NG ({0}).
        /// </summary>
        internal static string ST_SH_ScrappingFromNG_New_Form {
            get {
                return ResourceManager.GetString("ST_SH_ScrappingFromNG_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Scrapping From NG ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SH_ScrappingFromNG_New_Path {
            get {
                return ResourceManager.GetString("ST_SH_ScrappingFromNG_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapping From NG ({0}).
        /// </summary>
        internal static string ST_SH_ScrappingFromNG_View_Form {
            get {
                return ResourceManager.GetString("ST_SH_ScrappingFromNG_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Scrapping From NG ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SH_ScrappingFromNG_View_Path {
            get {
                return ResourceManager.GetString("ST_SH_ScrappingFromNG_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Shipping Adjustment ({0}).
        /// </summary>
        internal static string ST_SH_StockShippingAdjustment_New_Form {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingAdjustment_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Shipping Adjustment ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SH_StockShippingAdjustment_New_Path {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingAdjustment_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Shipping Adjustment ({0}).
        /// </summary>
        internal static string ST_SH_StockShippingAdjustment_View_Form {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingAdjustment_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Shipping Adjustment ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SH_StockShippingAdjustment_View_Path {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingAdjustment_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Shipping for Delivery ({0}).
        /// </summary>
        internal static string ST_SH_StockShippingForDelivery_New_Form {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingForDelivery_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Shipping for Delivery ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_SH_StockShippingForDelivery_New_Path {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingForDelivery_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Shipping for Delivery ({0}).
        /// </summary>
        internal static string ST_SH_StockShippingForDelivery_View_Form {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingForDelivery_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Shipping for Delivery ({0}) -&gt; View.
        /// </summary>
        internal static string ST_SH_StockShippingForDelivery_View_Path {
            get {
                return ResourceManager.GetString("ST_SH_StockShippingForDelivery_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG Recycle Materials ({0}).
        /// </summary>
        internal static string ST_ST_NGRecycleMaterial_New_Form {
            get {
                return ResourceManager.GetString("ST_ST_NGRecycleMaterial_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; NG Recycle Materials ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_ST_NGRecycleMaterial_New_Path {
            get {
                return ResourceManager.GetString("ST_ST_NGRecycleMaterial_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG Recycle Materials ({0}).
        /// </summary>
        internal static string ST_ST_NGRecycleMaterial_View_Form {
            get {
                return ResourceManager.GetString("ST_ST_NGRecycleMaterial_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; NG Recycle Materials ({0}) -&gt; View.
        /// </summary>
        internal static string ST_ST_NGRecycleMaterial_View_Path {
            get {
                return ResourceManager.GetString("ST_ST_NGRecycleMaterial_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transfer - Arriving In Storage ({0}).
        /// </summary>
        internal static string ST_ST_StockTransferArrivingInStorage_New_Form {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferArrivingInStorage_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Transfer - Arriving In Storage ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_ST_StockTransferArrivingInStorage_New_Path {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferArrivingInStorage_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Transfer - Arriving In Storage ({0}).
        /// </summary>
        internal static string ST_ST_StockTransferArrivingInStorage_View_Form {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferArrivingInStorage_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Stock Transfer - Arriving In Storage ({0}) -&gt; View.
        /// </summary>
        internal static string ST_ST_StockTransferArrivingInStorage_View_Path {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferArrivingInStorage_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTransfer - ShippingFromStorage ({0}).
        /// </summary>
        internal static string ST_ST_StockTransferShippingFromStorage_New_Form {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferShippingFromStorage_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; StockTransfer - ShippingFromStorage ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_ST_StockTransferShippingFromStorage_New_Path {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferShippingFromStorage_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTransfer - ShippingFromStorage ({0}).
        /// </summary>
        internal static string ST_ST_StockTransferShippingFromStorage_View_Form {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferShippingFromStorage_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; StockTransfer - ShippingFromStorage ({0}) -&gt; View.
        /// </summary>
        internal static string ST_ST_StockTransferShippingFromStorage_View_Path {
            get {
                return ResourceManager.GetString("ST_ST_StockTransferShippingFromStorage_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer For Production Line ({0}).
        /// </summary>
        internal static string ST_ST_TransferForProductionLine_New_Form {
            get {
                return ResourceManager.GetString("ST_ST_TransferForProductionLine_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Transfer For Production Line ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_ST_TransferForProductionLine_New_Path {
            get {
                return ResourceManager.GetString("ST_ST_TransferForProductionLine_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer For Production Line ({0}).
        /// </summary>
        internal static string ST_ST_TransferForProductionLine_View_Form {
            get {
                return ResourceManager.GetString("ST_ST_TransferForProductionLine_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Transfer For Production Line ({0}) -&gt; View.
        /// </summary>
        internal static string ST_ST_TransferForProductionLine_View_Path {
            get {
                return ResourceManager.GetString("ST_ST_TransferForProductionLine_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Posting ({0}).
        /// </summary>
        internal static string ST_ST_TransferPosting_New_Form {
            get {
                return ResourceManager.GetString("ST_ST_TransferPosting_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Transfer Posting ({0}) -&gt; Add.
        /// </summary>
        internal static string ST_ST_TransferPosting_New_Path {
            get {
                return ResourceManager.GetString("ST_ST_TransferPosting_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Posting ({0}).
        /// </summary>
        internal static string ST_ST_TransferPosting_View_Form {
            get {
                return ResourceManager.GetString("ST_ST_TransferPosting_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock -&gt; Stock Management -&gt; Transfer Posting ({0}) -&gt; View.
        /// </summary>
        internal static string ST_ST_TransferPosting_View_Path {
            get {
                return ResourceManager.GetString("ST_ST_TransferPosting_View_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ST_StockOverview_colAmount {
            get {
                return ResourceManager.GetString("ST_StockOverview_colAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In/Out.
        /// </summary>
        internal static string ST_StockOverview_colBalanceFlag {
            get {
                return ResourceManager.GetString("ST_StockOverview_colBalanceFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ST_StockOverview_colInputQuantity {
            get {
                return ResourceManager.GetString("ST_StockOverview_colInputQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string ST_StockOverview_colInputUnit {
            get {
                return ResourceManager.GetString("ST_StockOverview_colInputUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string ST_StockOverview_colItemCode {
            get {
                return ResourceManager.GetString("ST_StockOverview_colItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ST_StockOverview_colItemName {
            get {
                return ResourceManager.GetString("ST_StockOverview_colItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string ST_StockOverview_colRemark {
            get {
                return ResourceManager.GetString("ST_StockOverview_colRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string ST_StockOverview_colUnitPrice {
            get {
                return ResourceManager.GetString("ST_StockOverview_colUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Overview ({0}).
        /// </summary>
        internal static string ST_StockOverview_Search_Form {
            get {
                return ResourceManager.GetString("ST_StockOverview_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock &gt; Stock Management &gt; Stock Overview ({0}).
        /// </summary>
        internal static string ST_StockOverview_Search_Path {
            get {
                return ResourceManager.GetString("ST_StockOverview_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string SY_ChangePassword_Edit_Form {
            get {
                return ResourceManager.GetString("SY_ChangePassword_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &gt; Change Password.
        /// </summary>
        internal static string SY_ChangePassword_Edit_Path {
            get {
                return ResourceManager.GetString("SY_ChangePassword_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string SY_Parameters_Edit_Form {
            get {
                return ResourceManager.GetString("SY_Parameters_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &gt; Common &gt; Parameters.
        /// </summary>
        internal static string SY_Parameters_Edit_Path {
            get {
                return ResourceManager.GetString("SY_Parameters_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string SY_UserGroups_colDisplayName {
            get {
                return ResourceManager.GetString("SY_UserGroups_colDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SY_UserGroups_colStatus {
            get {
                return ResourceManager.GetString("SY_UserGroups_colStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        internal static string SY_UserGroups_colUserCode {
            get {
                return ResourceManager.GetString("SY_UserGroups_colUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Journal (Japanese).
        /// </summary>
        internal static string SYS_SystemJournals_Search_Form {
            get {
                return ResourceManager.GetString("SYS_SystemJournals_Search_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System -&gt; System Journal (Japanese).
        /// </summary>
        internal static string SYS_SystemJournals_Search_Path {
            get {
                return ResourceManager.GetString("SYS_SystemJournals_Search_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User (japan).
        /// </summary>
        internal static string SYS_User_Edit_Edit_Form {
            get {
                return ResourceManager.GetString("SYS_User_Edit_Edit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System -&gt; User -&gt; Edit User (japan).
        /// </summary>
        internal static string SYS_User_Edit_Edit_Path {
            get {
                return ResourceManager.GetString("SYS_User_Edit_Edit_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User (japan).
        /// </summary>
        internal static string SYS_User_Edit_New_Form {
            get {
                return ResourceManager.GetString("SYS_User_Edit_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System -&gt; User -&gt; Create User (japan).
        /// </summary>
        internal static string SYS_User_Edit_New_Path {
            get {
                return ResourceManager.GetString("SYS_User_Edit_New_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View User (japan).
        /// </summary>
        internal static string SYS_User_Edit_View_Form {
            get {
                return ResourceManager.GetString("SYS_User_Edit_View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System -&gt; User -&gt; View User (japan).
        /// </summary>
        internal static string SYS_User_Edit_View_Path {
            get {
                return ResourceManager.GetString("SYS_User_Edit_View_Path", resourceCulture);
            }
        }
    }
}
